# Mapeo de nombres utilizados en Fantasy y en app de stats.
# Servirá para la inicialización

MAPEO_APP_FANTASY = {
    'Abu Baker Zeis': 'Abu',
    'Alessandro Astorga': 'Alessandro',
    'Alfredo Gutierrez': 'Alfredo',
    'A. Diaz Díaz Reyna': 'Andres Diaz',
    'A. Freitas Freitas': 'Andres Freitas',
    '??': 'Andrez Lopez',
    'A. Ruiz Ruiz': 'Andres Ruiz',
    'A. Andy Dos Santos': 'Andy',
    'Antonio Da Silva Cabral': 'Antonio',
    'Arturo Da Silva': 'Arturo',
    'Azocar Azócar': 'Azocar',
    'Beto Cols': 'Beto',
    'Bosch Bosch': 'Bosch',
    'Bravo Bravo': 'Bravo',
    'Carlos Saritama': 'Carlos',
    'Arturo Suarez': 'Chino',
    'Christian Cappuccio': 'Christian',
    'Danielito Astorga': 'Daniel',
    'A. Tovar De Tovar': 'De Tovar',
    'Diego Oliveros': 'Diego',
    'Eddy Tovar': 'Eddy',
    'Emanuel Pereira': 'Emanuel',
    'Enrique Jose Iglesias Linares': 'Enrique',
    'Fico Antillano': 'Fico',
    'Frank Kenneth Spacey Helder': 'Fran',
    'Francisco Astorga': 'Frank',
    'Gabriel Iglesias': 'Gabriel I',
    'Gabriel Rodrigues': 'Gabriel Morocho',
    'Gabriel Vázquez': 'Gabriel Vazquez',
    'Gilberto Figueira': 'Gilberto',
    'Guillermo Bonell': 'Guillermo',
    'Hector Gomez': 'Hector',
    'Ignacio Velasco': 'Ignacio',
    'Imanol Pose Casarone': 'Imanol',
    'Jhon Ramos': 'Jhon',
    'João Paulo Vitor': 'Joao',
    'Joel Araujo': 'Joel',
    'Jony Hernandez': 'Jony',
    'Josif Gonzalez Gonzalez': 'Josif',
    'Lawrey Prior': 'Lawrey',
    'Luis Pastrán': 'Luis Gocho',
    'Luis López': 'Luis Lopez',
    'Matt Breakell': 'Matt',
    'Mauricio Barroso': 'Mauricio',
    'Miguel De Abreu': 'Miguel',
    'Ignacio Pose': 'Nacho',
    'Nico Riccelli': 'Nico',
    'Maiky López': 'Maiky',
    'Pedro Mejias': 'Pedro',
    'Ricardo Pereira': 'Ricardo',
    'Roman Diaz': 'Roman',
    'Roymer Gonzalez': 'Roy',
    'Samuel Matas': 'Samu',
    'Samuel Udelman': 'Samuel',
    'Samuel Rojas': 'Samuel Rojas',
    'Santiago De La Fuente': 'Santiago',
    'Sergio Gorrochategui': 'Sergio',
    'Thiago Barbosa Barella': 'Thiago',
    'Tito Marcano': 'Tito',
    'Vicente Comes': 'Vicente',
    'Víctor Escribano Ramos': 'Victor'}
