WEEK_PATH = 'data/jornadas/2025/result_season_1_week_1.xlsm'
HEADLESS = True

DASHBOARD_CLASS = "ozKqOrLtcBmCYpsCNU4w"

NAME_TABLE_CLASS = "BurUbDZ82YjD6LgyrWbQ"
STATS_TABLE_CLASS = "utG5NdhaXPfNxHf8O06C"
TABLE_CLASS = "_LSFb4IwrZAI41Kk9tgr"

NAME_ROWS_CLASS_SOUP = "div.fCdW_eIEyEWMQ_Y4Xjid"
NAME_TEXT_CLASS_SOUP = "a.NznEGSuhjoTFcwzPHzNd"

STATS_COLUMNS_CLASS_SOUP = "div.RYFw3QcNNvVNj3bsW8gM"
STATS_ROWS_CLASS_SOUP = "div.RYFw3QcNNvVNj3bsW8gM"
STATS_VALUE_CLASS_SOUP = "div.nohm4uA0k9j71NMyNuzL"

STAR_NAME_CLASS = "Ge68L6q7HYFPnKWBVagq"
STAR_VOTE_CLASS = "wgJVUNsyjXu6Uxw905ah"

season_LIST_BTN_CLASS = "dHKpGiMJzb7k67eMw5SZ"
YEAR_SEASON_NAME_CLASS = "bfA2rUSWqJO164zLByUR"

CALENDAR_TABLE_ID = "ListCalendar"
CALENDAR_WEEK_CLASS = "T4FET2L5vbM6D9ncwq5S"