JORNADA_PATH = "data/jornadas/2024/seasson6/jornada21.xlsx"
HEADLESS = True

TABLE_CLASS = "_LSFb4IwrZAI41Kk9tgr"

NAME_ROWS_CLASS_SOUP = "div.fCdW_eIEyEWMQ_Y4Xjid"
NAME_TEXT_CLASS_SOUP = "a.NznEGSuhjoTFcwzPHzNd"

STATS_ROWS_CLASS_SOUP = "div.RYFw3QcNNvVNj3bsW8gM"
STATS_VALUE_CLASS_SOUP = "div.nohm4uA0k9j71NMyNuzL"

STAR_NAME_CLASS = "Ge68L6q7HYFPnKWBVagq"
STAR_VOTE_CLASS = "wgJVUNsyjXu6Uxw905ah"

SEASSON_LIST_BTN_CLASS = "dHKpGiMJzb7k67eMw5SZ"
YEAR_SEASON_NAME_CLASS = "bfA2rUSWqJO164zLByUR"

CALENDAR_TABLE_ID = "ListCalendar"
CALENDAR_WEEK_CLASS = "T4FET2L5vbM6D9ncwq5S"